name: Cloudflare Worker Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'worker/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Worker

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Cloudflare Wrangler
        run: npm install -g wrangler

      - name: Deploy Worker to s.berkk.cloud
        working-directory: ./worker
        run: wrangler deploy --minify --route "s.berkk.cloud/*"
        env:

          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN_WORKERS }} 

          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}